# https://beta.ruff.rs
name: ruff
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uvx ruff check --output-format=github .
